# Welcome to Dental Atlas!
#
# This page will serve as a personal journal and a resource for those passionate about their oral health. 
From exploring different kinds of toothpaste and mouthwash, to sharing my dental school notes.
This is where I will do my best to track new discoveries and uncover misconceptions!
#
# 
#
#
#


title: Dental Atlas
email: MonicaLikesTeeth@gmail.com
description: >- # DISCLAIMER: I AM NOT A DENTIST- Dental Atlas is an educational and personal project created by a student. 
Content on this site is for informational purposes only and should not be taken as professional dental or medical advice. 
Always consult a licensed dentist or healthcare professional for diagnosis or treatment of oral health concerns. 
Any opinions expressed are my own and do not represent the views of any academic institution or organization.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
